### ISSUE TITLE
Featuer request: Using keyboard short

### ISSUE THREAD

**Issue by nelaaro** [Eugeny/terminus-shell-selector#2]
Would be great If I could use a keyboard short cut to call up this functionality.

**Comment by jordandrako** [comment]
For some reason, it's not in the UI, but by default the hotkey is Alt-N. You can change it in the config file:
```yml
hotkeys:
  shell-selector:
    - Alt-N
```
